package com.allinone.app.fb;

import android.content.Context;
import android.text.TextUtils;
import android.webkit.CookieManager;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 * Bridges the WebView cookie jar (populated when the user logs into Facebook inside
 * {@link com.allinone.app.FbBrowserActivity}) into a Netscape-format {@code cookies.txt}
 * file that yt-dlp can consume via {@code --cookies}.
 *
 * <p>Without this, yt-dlp can only see fully public videos. With a valid session cookie
 * it can resolve private / group / friends-only videos exactly as the logged-in user sees them.
 */
public final class FbCookieStore {

    /** Domains whose cookies are exported. Facebook splits auth across these. */
    private static final String[] SOURCE_URLS = {
            "https://www.facebook.com",
            "https://facebook.com",
            "https://m.facebook.com"
    };

    /** Session cookie Facebook sets only for a logged-in account (holds the user id). */
    private static final String LOGIN_MARKER = "c_user";

    /** The actual secret session token. Without it the jar authenticates nothing. */
    private static final String SESSION_TOKEN = "xs";

    private static final String COOKIE_DIR  = "fbdl";
    private static final String COOKIE_FILE = "cookies.txt";

    /** Far-future expiry — the WebView jar is the real source of truth for validity. */
    private static final long EXPIRY = 2145916800L; // 2038-01-01

    private FbCookieStore() {}

    // ── Paths ─────────────────────────────────────────────────────────────────

    public static File cookieFile(Context ctx) {
        File dir = new File(ctx.getFilesDir(), COOKIE_DIR);
        if (!dir.exists()) dir.mkdirs();
        return new File(dir, COOKIE_FILE);
    }

    /** Returns the cookies.txt only if it exists and is non-empty, else null. */
    public static File existingCookieFile(Context ctx) {
        File f = cookieFile(ctx);
        return (f.exists() && f.length() > 0) ? f : null;
    }

    // ── Login state ───────────────────────────────────────────────────────────

    /** True when the WebView jar currently holds a Facebook session cookie. */
    public static boolean isLoggedIn() {
        return !TextUtils.isEmpty(findCookie(LOGIN_MARKER));
    }

    /** Returns the logged-in Facebook numeric user id, or null. */
    public static String userId() {
        return findCookie(LOGIN_MARKER);
    }

    /**
     * True only when the jar holds the {@code xs} session token as well as {@code c_user}.
     * {@code c_user} alone survives a partial/expired login and looks logged-in while
     * authenticating nothing — yt-dlp would then fail as if the video were missing.
     */
    public static boolean hasUsableSession() {
        return !TextUtils.isEmpty(findCookie(LOGIN_MARKER))
                && !TextUtils.isEmpty(findCookie(SESSION_TOKEN));
    }

    /** Human-readable summary of which auth cookies we actually captured — for diagnostics. */
    public static String describe(Context ctx) {
        StringBuilder sb = new StringBuilder();
        sb.append("c_user: ").append(findCookie(LOGIN_MARKER) != null ? "yes" : "MISSING");
        sb.append("\nxs: ").append(findCookie(SESSION_TOKEN) != null ? "yes" : "MISSING");
        File f = existingCookieFile(ctx);
        sb.append("\ncookies.txt: ").append(f != null ? (f.length() + " bytes") : "MISSING");
        return sb.toString();
    }

    private static String findCookie(String name) {
        CookieManager cm = CookieManager.getInstance();
        for (String url : SOURCE_URLS) {
            String raw = cm.getCookie(url);
            if (TextUtils.isEmpty(raw)) continue;
            for (String pair : raw.split(";")) {
                int eq = pair.indexOf('=');
                if (eq <= 0) continue;
                if (pair.substring(0, eq).trim().equals(name)) {
                    String value = pair.substring(eq + 1).trim();
                    if (!TextUtils.isEmpty(value)) return value;
                }
            }
        }
        return null;
    }

    // ── Export ────────────────────────────────────────────────────────────────

    /**
     * Writes the current WebView Facebook cookies to a Netscape cookies.txt.
     *
     * @return the written file, or null if there was nothing to write.
     */
    public static File export(Context ctx) throws IOException {
        CookieManager cm = CookieManager.getInstance();

        StringBuilder sb = new StringBuilder();
        sb.append("# Netscape HTTP Cookie File\n");
        sb.append("# Generated by All in One — FB Downloader\n\n");

        boolean wroteAny = false;
        // Dedupe by cookie name; Facebook returns the same names across its hosts.
        java.util.Set<String> seen = new java.util.HashSet<>();

        for (String url : SOURCE_URLS) {
            String raw = cm.getCookie(url);
            if (TextUtils.isEmpty(raw)) continue;

            for (String pair : raw.split(";")) {
                int eq = pair.indexOf('=');
                if (eq <= 0) continue;
                String name  = pair.substring(0, eq).trim();
                String value = pair.substring(eq + 1).trim();
                if (TextUtils.isEmpty(name) || !seen.add(name)) continue;

                // domain \t includeSubdomains \t path \t secure \t expiry \t name \t value
                sb.append(".facebook.com").append('\t')
                  .append("TRUE").append('\t')
                  .append('/').append('\t')
                  .append("TRUE").append('\t')
                  .append(EXPIRY).append('\t')
                  .append(name).append('\t')
                  .append(value).append('\n');
                wroteAny = true;
            }
        }

        if (!wroteAny) return null;

        File out = cookieFile(ctx);
        try (BufferedWriter w = new BufferedWriter(new FileWriter(out, false))) {
            w.write(sb.toString());
        }
        return out;
    }

    // ── Logout ────────────────────────────────────────────────────────────────

    /** Clears the WebView cookie jar and deletes the exported cookies.txt. */
    public static void clear(Context ctx) {
        CookieManager cm = CookieManager.getInstance();
        cm.removeAllCookies(null);
        cm.flush();
        File f = cookieFile(ctx);
        if (f.exists()) f.delete();
    }
}
